name: Build CentOS 7 RPM

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CentOS 7 Build
      id: rpm
      uses: locobastos/rpmbuild@master
      with:
        spec_file: SPEC/haproxy.spec
